steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--tag=gcr.io/$PROJECT_ID/niijumita:$COMMIT_SHA",
        "--tag=gcr.io/$PROJECT_ID/niijumita:latest",
        "--file=./docker/Dockerfile",
        ".",
      ]
  # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/niijumita:latest"]
